version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
      - "9229:9229"  # Node.js debugging port
    volumes:
      - ./:/app:cached
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      # Required for Vite HMR
      - ORIGIN=http://localhost:5173
    command: yarn dev --host
    # Enable container debugging
    stdin_open: true
    tty: true

volumes:
  node_modules:
